### ISSUE TITLE
undefined method `empty?' for nil:NilClass [Rails 4.2.2]

### ISSUE THREAD

**Issue by ryanh** [phatworx/easy_captcha#24]
Getting this error after install using Rails 4.2.2 and the devise_security_extension gem

Extracted source (around line #176):
  prefixes = prefixes.presence
  parts    = name.to_s.split('/')
  parts.shift if parts.first.empty?
  name     = parts.pop

  return name, prefixes || [""] if parts.empty?

actionview (4.2.2) lib/action_view/lookup_context.rb:176:in `normalize_name'
actionview (4.2.2) lib/action_view/lookup_context.rb:151:in `args_for_lookup'
actionview (4.2.2) lib/action_view/lookup_context.rb:130:in `exists?'
actionview (4.2.2) lib/action_view/view_paths.rb:13:in `template_exists?'
actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:14:in `method_for_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:230:in `_find_action_name'
actionpack (4.2.2) lib/abstract_controller/base.rb:131:in `process'
actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.2) lib/action_controller/metal.rb:227:in `call'
actionpack (4.2.2) lib/action_controller/metal.rb:227:in `call'
actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/application.rb:164:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'

**Comment by dmz006** [comment]
Is this the same as https://github.com/phatworx/devise_security_extension/issues/107? If so traxanos mentioned there was a fix in git, but I've not found it yet.

**Comment by dmz006** [comment]
(byebug) name
""
(byebug) prefixes
["easy_captcha/"]
(byebug) parts    = name.to_s.split('/')
[]
(byebug) parts
[]
(byebug) parts.shift if parts.first.empty?
*** NoMethodError Exception: undefined method `empty?' for nil:NilClass

nil

**Comment by dmz006** [comment]
I just removed easy_captcha & installed from https://github.com/phatworx/easy_captcha.git
Gemfile
gem 'easy_captcha', :github => 'phatworx/easy_captcha'

**Comment by TangMonk** [comment]
install from github will work

**Comment by alexdreher** [comment]
0.6.5 is now released with the fix.
